### PR TITLE
move stBounds tests to memory stress section

### PR DESCRIPTION
**Pull request by winsvega**
now to execute stBoundsTest need to set --all option

### CODE REVIEW

**Comment by chriseth** [comment]
Are these two unrelated changes?

**Comment by winsvega** [comment]
stBounds consume a lot of memory on some OP codes.

**Comment by gcolvin** [comment]
I thought that these tests consume a lot of memory because in
> (JUMP 0x01000000000000000b) (JUMPDEST) (JUMPDEST) (SSTORE 1 1)
The JUMP destination gets truncated to 0xb and gets to to the SSTORE.  Absent that bug they should throw BadJumpDestination.

**Comment by chriseth** [comment]
Ok, please single out the tests that have large initial gas values. All other tests should always be executed and if they consume too much memory, that needs to be fixed. It might be good to just check during execution whether the gas value is large and if yes, log a message that the test was skipped and how to run the test binary without skipping those tests.

**Comment by winsvega** [comment]
there are options for testeth 
```
cout << std::endl << "Additional Tests" << std::endl;
	cout << setw(30) << "--performance" << setw(25) << "Enable perfomance tests" << std::endl;
	cout << setw(30) << "--quadratic" << setw(25) << "Enable quadratic complexity tests" << std::endl;
	cout << setw(30) << "--memory" << setw(25) << "Enable memory consuming tests" << std::endl;
	cout << setw(30) << "--inputLimits" << setw(25) << "Enable inputLimits tests" << std::endl;
	cout << setw(30) << "--bigdata" << setw(25) << "Enable bigdata tests" << std::endl;
	cout << setw(30) << "--wallet" << setw(25) << "Enable wallet tests" << std::endl;
	cout << setw(30) << "--all" << setw(25) << "Enable all tests" << std::endl;
```

**Comment by gcolvin** [comment]
But wait -- I'm saying it looks like this test consumes memory only because of a bug, unless I misread it.

**Comment by winsvega** [comment]
JUMP seem not to consume any memory in this case. some of the stBounds are. need to separate it into another file under --memory option

**Comment by gcolvin** [comment]
OK.  I am fixing a truncation bug in the jump verification routine.

**Pull request merged**
